### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by linakherchi** [lee-joseph-i/dietsana#1]
- [x] Contains correct datatypes 
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null 
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
    - [x] foreign key and table name are lowercased, snake_cased and back_ticked
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and back_ticked
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and back_ticked

**Comment by linakherchi** [comment]
Thanks, Joseph ! One comment regarding table names is that these need to be lowercased and back_ticked

**Comment by lee-joseph-i** [comment]
Done! 
I'm still not quite sure what method to use to save a profile picture (image or link) for each user, so that's not quite right yet in the Users table.

**Comment by linakherchi** [comment]
If you are not going to have a lot of pictures, you can use the assets pipeline to save your images. If you are going to use many images, it is better to opt out for AWS, which will make your app run faster.

**Comment by linakherchi** [comment]
Table names still need to be lowercased and back ticked
