### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by lee-joseph-i** [lee-joseph-i/dietsana#7]
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentational Components and Containers
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds

**Comment by linakherchi** [comment]
Hi Joseph ! Could you please change the link to the Heroku page that is on your Wiki Page so that I can access it ? Thank you !

**Comment by lee-joseph-i** [comment]
@linakherchi Oops! it's updated now. Thanks!
